### ISSUE TITLE
Issue with Connection

### ISSUE THREAD

**Issue by hoosiersunited** [Ascoware/get-iplayer-automator#211]
I am getting the following message when I try to download from iPlayer. ITV has been working fine, and I can access iPlayer through the web browser. Any ideas?

BBC Download (ID=b0bpw76q): Downloading There She Goes: Series 1 - Bubble Chess
INFO: 1 total programmes
ERROR: Failed to download URL (3/3): https://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/iptv-all/vpid/p06p76lj?cb=57180
ERROR: Response: 500 Can't connect to open.live.bbc.co.uk:443
ERROR: Ignore this error if programme download is successful
ERROR: Failed to download URL (3/3): https://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/pc/vpid/p06p76lj?cb=84989
ERROR: Response: 500 Can't connect to open.live.bbc.co.uk:443
ERROR: Ignore this error if programme download is successful
ERROR: Failed to download URL (3/3): https://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/apple-ipad-hls/vpid/p06p76lj?cb=15348
ERROR: Response: 500 Can't connect to open.live.bbc.co.uk:443
ERROR: Ignore this error if programme download is successful
ERROR: Failed to download URL (3/3): https://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/iptv-all/vpid/p06p76ll?cb=03134
ERROR: Response: 500 Can't connect to open.live.bbc.co.uk:443
ERROR: Ignore this error if programme download is successful

**Comment by Vangelis66** [comment]
Quite possibly, a duplicate of #200 ; same error logs...

**Comment by hoosiersunited** [comment]
Going back to version 1.13.10 worked. Thanks and apologies for not seeing the earlier entry.

**Comment by zugernaut** [comment]
I have compared the logs when running GIA 1.13.10 to those of running more recent versions.
There seems to be something different with accessing <open.live.bbc.co.uk> in the two versions.

The problem seems to be with get_iplayer itself when used with a VPN (either inside or outside of the UK). I have tried get_iplayer command line version with same outcome.

In GIA version 1.13.10 the call to <open.live.bbc.co.uk> works fine even when using a VPN.

INFO: Getting URL: https://www.bbc.co.uk/programmes/b0bp3f85.json
INFO: Getting stream data for version: 'original'
INFO: Getting URL: https://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/iptv-all/vpid/b0bp3f83?cb=08838
(no error)

Only two of the resulting stream locations can be accessed, however, but this still delivers a number of valid, accessible streams.

In GIA version 1.13.16 the call to <open.live.bbc.co.uk> works inside the UK when not using a VPN
It is able to access all of the stream locations and gives a longer list of available streams.

INFO: Downloading URL (1/3): https://www.bbc.co.uk/programmes/b0bp3f85.json
INFO: Getting stream data for version: 'original'
INFO: Downloading URL (1/3): https://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/iptv-all/vpid/b0bp3f83?cb=68350
(no error)


However, if you use 1.13.16 with a VPN (inside or outside of the UK), the call to <open.live.bbc.co.uk> now does not work (even though it appears to be exactly the same syntax as in 1.13.10.  As a result, there are no streams for get_iplayer to work with and program ends.

INFO: Downloading URL (1/3): https://www.bbc.co.uk/programmes/b0bp3f85.json
INFO: Getting stream data for version: 'original'
INFO: Downloading URL (1/3): https://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/iptv-all/vpid/b0bp3f83?cb=47651
WARNING: Failed to download URL (1/3): https://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/iptv-all/vpid/b0bp3f83?cb=47651
WARNING: Response: 500 Can't connect to open.live.bbc.co.uk:443

So, it’s a little strange that the call to <open.live.bbc.co.uk> works fine with a VPN in version 1.13.10, but not in version 1.13.16

I am running macOS Sierra 10.12.6

**Comment by nycradik** [comment]
I see from both @hoosiersunited and @zugernaut that their GiA instances are showing Error 500 in the logs for version 1.13.16 above.

I am seeing Error 403 Forbidden in both 1.13.10 and 1.13.16 when connecting via NordVPN from the US.  There are no DNS leaks during my current connection when trying both versions and I forced a cache update in GiA as well as a browser cache flush.

When searching for an episode in GiA and clicking the 'i' symbol for information about the episode, the Available Modes box is empty.

I am running macOS Mojave 10.14.1

> Get iPlayer Automator 1.13.16 Initialized.
> <AppController: 0x7fd00615eaa0>: Updating Programme Index Feeds...
> 
> <AppController: 0x7fd00615eaa0>: Index was Up-To-Date.
> 
> 
> INFO: Loading proxy settings...
> INFO: No proxy to load
> INFO: Proxy load complete.
> INFO: No proxy will be used
> AppController: Starting Downloads
> 
> 
> Downloading Show 1/1:
> 
> BBC Download (ID=b0brghc8): Downloading Doctor Who: Series 11 - The Tsuranga Conundrum
> INFO: 1 total programmes
> ERROR: Failed to download URL (3/3): https://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/iptv-all/vpid/p06qf5b3?cb=24256
> ERROR: Response: 403 Forbidden
> ERROR: Ignore this error if programme download is successful
> ERROR: Failed to download URL (3/3): https://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/pc/vpid/p06qf5b3?cb=46891
> ERROR: Response: 403 Forbidden
> ERROR: Ignore this error if programme download is successful
> ERROR: Failed to download URL (3/3): https://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/apple-ipad-hls/vpid/p06qf5b3?cb=89642
> ERROR: Response: 403 Forbidden
> ERROR: Ignore this error if programme download is successful
> ERROR: Failed to download URL (3/3): https://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/iptv-all/vpid/b0brghbp?cb=10372
> ERROR: Response: 403 Forbidden
> ERROR: Ignore this error if programme download is successful
> ERROR: Failed to download URL (3/3): https://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/pc/vpid/b0brghbp?cb=09205
> ERROR: Response: 403 Forbidden
> ERROR: Ignore this error if programme download is successful
> ERROR: Failed to download URL (3/3): https://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/apple-ipad-hls/vpid/b0brghbp?cb=96514
> ERROR: Response: 403 Forbidden
> ERROR: Ignore this error if programme download is successful
> WARNING: No media streams found for requested programme versions and recording modes.
> WARNING: The programme may no longer be available - check the iPlayer site.
> WARNING: If you are outside the UK, check with the provider to find out if your VPN/VPS/Smart DNS/web proxy has been blocked.
> BBC Download (ID=b0brghc8): Doctor Who: Series 11 - The Tsuranga Conundrum Failed
> AppController: Downloads Finished

**Comment by skovatch** [comment]
I did some system maintenance this morning that involved updating openssl and libressl, and that caused their root certificates to be regenerated based on the macOS system keychain certificates. That had the effect of both GiA and GiP no longer getting a 500 error when a show starts downloading. I still get some 403 errors connecting to some of the CDNs, but the shows still download.

v1.13.5 is the first release with get_iplayer 3.14, and that version started using https everywhere. All of the problems started in v1.13.11, which is where I updated get_iplayer to 3.15. This line in get_iplayer's release notes is suspect:

> Adapted for SSL certificate verification changes in Mojolicious >= 7.80

Looking through Mojolicious' history, it looks like they had some serious security issues around https that were addressed in 7.80, so it's good that they fixed them, and I don't think we should go back.

What I can do is release an update with a newer set of CA certificates in the perl Mozilla CA with the hope it will help somewhat.

Note that I can only do so much in GiA because ultimately, get_iplayer is the code at issue here. Even if I update openssl, the command-line get_iplayer will still report 403 errors.

If you have brew on your system available, you might try upgrading openssl with `brew upgrade openssl`. 

If you are *inside the UK* (i.e., not using VPN) and are seeing this problem,  I would suggest reporting this to the developers on get_iplayer, as I suspect if I do it, it will just be shut down since I'm outside the UK.

**Comment by stevecopley** [comment]
Hi. Just to let you know that I'm still getting 500 errors for BBC programmes with 1.13.17 and the updated certs. Back to 1.13.10 and all is fine. (This is from NZ via NordVPN)

**Comment by zugernaut** [comment]
Hi all.
Sadly, I have the same outcome as Steve.  Getting same 500 errors with 1.13.17.  Have installed Homebrew and successfully run the upgrade to openssl as recommended. The upgrade did confirm that the old version of openssl was outdated.  Even after the upgrade, I still get the 500 errors.  Like Steve, reverting to 1.13.10 resolves the problem.  Do we perhaps need to do something specific to update any other certificates that might have expired?  Incidentally, I do note that both Steve and I are running NordVPN, but hopefully that is just coincidental.  Thanks for all your efforts, Scott.

**Comment by ElsonRoa** [comment]
Not sure that this is appropriate here but it might help others with various download issues. 

1.13.10 is the most reliable version for me (on Mac OSX 10.11.6 El Cap, VPN, outside UK) but 1.13.10 will not detect iplayer links in the browser. 

Therefore I am using 1.13.17 (which won’t download for me) to collect links and fill up my DL queue. 

Then I close 1.13.17 and open 1.13.10; it loads up the DL queue I just assembled in 1.13.17 and DLs it fine. 

This way round avoids the process of having to copy each PID and paste it into GPA one by one.

**Comment by zugernaut** [comment]
I am continuing my investigations.  Installing version 1.13.17 has not helped. I am running Mac Sierra 10.12.6

I have found that Safari is unable to open the following address...

https://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/iptv-all/vpid/b0bqrq1r?cb=15923

This is one of the queries that returns the stream data that get_iplayer uses, so I guess this is why get_iplayer is failing.

I installed the latest Firefox for Mac and this IS able to open this link.  However, even after installing Firefox it doesn't resolve the get_iplayer problem. I had hoped the Firefox certificates might have resolved things.

My next plan is to re-install the required certificates manually, but have not idea what these certificates are and where to find them.  Can someone help with this info?

**Comment by ElsonRoa** [comment]
Thank you for that tip, Skovtach. It sounds very promising.

**Comment by hugofalkman** [comment]
@skovatch After switching DNS provider a few times also I wound up with this outfit (although am not in the US). Their Level 1 support doesn't seem to be required to rigidly follow a standard script. When you tell them BBC has blacklisted you [again], you get pleasantly surprised when Level 1 answers, Yes we know, we are working on getting BBC back up.

**Comment by hugofalkman** [comment]
New support ticket Dec. 29, approx 5.30 am EST:
... This morning BBC once more have blacklisted your servers. Hope you are working on restoring the service.

Dec. 29, 7.30 am EST
... The technical team has made adjustments and I want you to try again but first do the instructions below ...

Dec. 29, 7.35 am EST
... Thank you for excellent support!

Dec. 29, 7.48 am EST:
... Glad to hear that it is all sorted out. Thank you for taking the time to get back to us and letting us know. Much appreciated. ...

**Comment by skovatch** [comment]
Please retest with v1.17. I found an option in mojolicious that should help here, and added it to the environment for launching get_iplayer. But since I don't see this problem I can't say for sure if it will fix the problem.
