### ISSUE TITLE
AppleTV Mac App Intermittently Incorrectly Imports to 'Home Videos' 

### ISSUE THREAD

**Issue by SOLOSAIR** [Ascoware/get-iplayer-automator#292]
*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*
Normal download
*What is the expected output? What do you see instead?*
Import to 'TV shows' expected and most do but regularly downloads go to 'Home Videos' necessitating manual change by right click >> get info >> options tab >> media kind: tv programme >> ok to bring all telly together 
*What version of GiA are you using? On what version of OS X?*
GIA:  Version 1.19.1 (20200906001)
MacOS: Catalina: 10.15.7 (19H2)
*Are you using a web proxy? DNS proxy? VPN? VPS?*
Don't know
*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *
Very often (but not always) Coronation Street, but others too
*Please provide any additional information below.*
Has happened ever since macOS switch from iTunes to TV app and I've been waiting for a fix.  (Apologies if this issue already discussed - I couldn't find it.)
![Screenshot 2020-10-16 at 22 05 55](https://user-images.githubusercontent.com/37366634/96309771-d9ca7a00-0ffd-11eb-8c69-054d9a0ec534.jpg)

**Comment by skovatch** [comment]
Yup, I see this now too. Atomic Parsley tagging is failing for some reason on ITV downloads. I don't know if it's just Corrie or all ITV shows.

**Comment by ian02054** [comment]
I had it on other shows as well...john bishops whale rescue for one. When I
checked I found at least 4 shows ragged as home movies. All itv.

**Comment by skovatch** [comment]
I see what's wrong... ITV changed the format of the JSON metadata for the program. I'll have an update soon.

**Comment by SOLOSAIR** [comment]
> I see what's wrong... ITV changed the format of the JSON metadata for the program. I'll have an update soon.

This is great news!  Thank you very much! 😃👍🏻

**Comment by skovatch** [comment]
Fixed in v1.19.2

**Comment by hugofalkman** [comment]
GiA check for updates doesn't find 1.19.2, and reports 1.19.1 as current

**Comment by skovatch** [comment]
Try again... Not sure why the app cast stream didn't update right away, but I forced it.

**Comment by hugofalkman** [comment]
Yep, now GiA found 1.19.2.

**Comment by SOLOSAIR** [comment]
Unfortunately still happening![image](https://user-images.githubusercontent.com/37366634/97770799-847a8680-1b2e-11eb-8cac-9d91c5340a59.jpeg)

**Comment by skovatch** [comment]
Are you sure you're running version 1.19.2?

**Comment by SOLOSAIR** [comment]
> Are you sure you're running version 1.19.2?

Yes this is the version I have.
![Screenshot 2020-11-03 at 12 17 05](https://user-images.githubusercontent.com/37366634/97984368-9b3f0880-1dce-11eb-9381-ffc61ebb0ce3.jpg)

**Comment by skovatch** [comment]
> Yes this is the version I have.
> ![Screenshot 2020-11-03 at 12 17 05](https://user-images.githubusercontent.com/37366634/97984368-9b3f0880-1dce-11eb-9381-ffc61ebb0ce3.jpg)

If it happens regularly, can you please:
- turn on verbose mode, and open the log window
- try downloading a show
- save the contents of the log to a file
- upload that file here

Thanks in advance.
